[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "React Basics Docs"
authors = [{name = "J. Gorol", email = ""}]
dynamic = ["version", "description"]
